services:
  auth-server:
    build:
      context: Auth
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"